[tool.poetry]
authors = ["SaitoTsutomu <tsutomu7@hotmail.co.jp>"]
classifiers = [
  "Development Status :: 1 - Planning",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python",
  "Topic :: Software Development",
  "Topic :: Scientific/Engineering",
]
description = "`tsp-tools` is a package for Traveling Salesman Problem for Python."
homepage = "https://github.com/SaitoTsutomu/tsp-tools"
license = "MIT"
name = "tsp-tools"
readme = "README.rst"
version = "0.0.9"

[tool.poetry.dependencies]
more-itertools = "^8.13"
pandas = "^1.4"
python = "^3.10"

[tool.poetry.dev-dependencies]
black = "^22.3"
flake8 = "^4.0"
isort = "^5.10"
mypy = "^0.961"
pytest = "^7.1"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
